services:
  bot:
    image: media-bot
    container_name: media-bot

    restart: unless-stopped

    env_file:
      - .env

    network_mode: host

    volumes:
      - ./storage/temp:/app/storage/temp
      - ./models:/app/models