services:
  bot:
    image: media_bot
    container_name: media_bot

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./storage/temp:/app/storage/temp
      - ./models:/app/models